import { Inter } from "next/font/google";
import Wrapper from "./wrapper";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Wrapper>
        <body className={`${inter.className} dark:bg-[#1b1a1b]`}>
          {children}
        </body>
      </Wrapper>
    </html>
  );
}
